env:
  browser: true
  commonjs: true
  es6: true
extends:
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions: {
    "ecmaVersion": 6,
    "sourceType": "module"
}
rules: {
    "comma-dangle": ["error", "never"],
    "require-jsdoc" : 0
}
